[2018/02/17 14:43:01] [?/ERROR]: name 'wait_for_start' is not defined at file "lib/virus.ccu" line 178, col 63
Traceback (most recent call last):
  File "C:/Users/Austin-zs/Documents/Austin/powder game code/Programming/Python3/PyCharmGeneral/CCU2/main.py", line 69, in <module>
    main()
  File "C:/Users/Austin-zs/Documents/Austin/powder game code/Programming/Python3/PyCharmGeneral/CCU2/main.py", line 34, in main
    text, fileName, outputPath = Common.file.getContent()
  File "C:\Users\Austin-zs\Documents\Austin\powder game code\Programming\Python3\PyCharmGeneral\CCU2\Common\file.py", line 42, in getContent
    text = pyexpander.expandToStr(source_file_text, filename=fileName)[0]
  File "C:\Python36\lib\site-packages\pyexpander\lib.py", line 1860, in expandToStr
    include_paths)
  File "C:\Python36\lib\site-packages\pyexpander\lib.py", line 1406, in processToList
    result.append(block.str_eval(tp.string()))
  File "C:\Python36\lib\site-packages\pyexpander\lib.py", line 462, in str_eval
    val= self.eval_(st)
  File "C:\Python36\lib\site-packages\pyexpander\lib.py", line 450, in eval_
    raise e.__class__("%s at %s" % (str(e), self.posmsg()))
NameError: name 'wait_for_start' is not defined at file "lib/virus.ccu" line 178, col 63
